/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.duoc.views;

/**
 *
 * @author Cetecom
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnAgregarProducto = new javax.swing.JMenuItem();
        mnEditarProducto = new javax.swing.JMenuItem();
        mnEliminarProducto = new javax.swing.JMenuItem();
        mnListarProducto = new javax.swing.JMenuItem();
        mnSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 255));

        jMenuBar1.setForeground(new java.awt.Color(102, 102, 255));

        jMenu1.setText("Producto");

        mnAgregarProducto.setText("Agregar");
        mnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAgregarProductoActionPerformed(evt);
            }
        });
        jMenu1.add(mnAgregarProducto);

        mnEditarProducto.setText("Editar");
        mnEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEditarProductoActionPerformed(evt);
            }
        });
        jMenu1.add(mnEditarProducto);

        mnEliminarProducto.setText("Eliminar");
        mnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEliminarProductoActionPerformed(evt);
            }
        });
        jMenu1.add(mnEliminarProducto);

        mnListarProducto.setText("Listar");
        mnListarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListarProductoActionPerformed(evt);
            }
        });
        jMenu1.add(mnListarProducto);

        jMenuBar1.add(jMenu1);

        mnSalir.setText("Salir");
        jMenuBar1.add(mnSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAgregarProductoActionPerformed
        AgregarProducto a = new AgregarProducto();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnAgregarProductoActionPerformed

    private void mnListarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListarProductoActionPerformed
        ListarProductos l = new ListarProductos();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnListarProductoActionPerformed

    private void mnEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEditarProductoActionPerformed
        ActualizarProducto a = new ActualizarProducto();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnEditarProductoActionPerformed

    private void mnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEliminarProductoActionPerformed
        EliminarProducto e = new EliminarProducto();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnEliminarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnAgregarProducto;
    private javax.swing.JMenuItem mnEditarProducto;
    private javax.swing.JMenuItem mnEliminarProducto;
    private javax.swing.JMenuItem mnListarProducto;
    private javax.swing.JMenu mnSalir;
    // End of variables declaration//GEN-END:variables
}
